import type { Article } from '../@types/Article';

// Mock articles for testing when the real RSS feed is not available
export const mockArticles: Article[] = [
  {
    id: 'mock-1',
    title: 'Building Scalable React Applications with TypeScript',
    description: 'Learn how to create maintainable and scalable React applications using TypeScript. This article covers best practices, project structure, and advanced patterns for enterprise-grade applications.',
    link: 'https://medium.com/@hpitawela/building-scalable-react-applications',
    pubDate: new Date('2024-01-15'),
    thumbnail: 'https://via.placeholder.com/400x200/1976d2/ffffff?text=React+TypeScript',
    author: 'Harsha Pitawela',
    categories: ['React', 'TypeScript', 'Frontend Development'],
  },
  {
    id: 'mock-2',
    title: 'AWS Lambda Best Practices for Production',
    description: 'Discover essential AWS Lambda best practices for building production-ready serverless applications. Learn about performance optimization, error handling, and monitoring strategies.',
    link: 'https://medium.com/@hpitawela/aws-lambda-best-practices',
    pubDate: new Date('2024-01-10'),
    thumbnail: 'https://via.placeholder.com/400x200/ff9800/ffffff?text=AWS+Lambda',
    author: 'Harsha Pitawela',
    categories: ['AWS', 'Serverless', 'Cloud Computing'],
  },
  {
    id: 'mock-3',
    title: 'Microservices Architecture with Node.js',
    description: 'A comprehensive guide to implementing microservices architecture using Node.js. Explore service communication, data management, and deployment strategies.',
    link: 'https://medium.com/@hpitawela/microservices-nodejs',
    pubDate: new Date('2024-01-05'),
    thumbnail: 'https://via.placeholder.com/400x200/4caf50/ffffff?text=Node.js+Microservices',
    author: 'Harsha Pitawela',
    categories: ['Node.js', 'Microservices', 'Backend Development'],
  },
  {
    id: 'mock-4',
    title: 'DevOps Automation with GitHub Actions',
    description: 'Streamline your development workflow with GitHub Actions. Learn how to set up CI/CD pipelines, automated testing, and deployment processes for your projects.',
    link: 'https://medium.com/@hpitawela/devops-github-actions',
    pubDate: new Date('2023-12-28'),
    thumbnail: 'https://via.placeholder.com/400x200/9c27b0/ffffff?text=GitHub+Actions',
    author: 'Harsha Pitawela',
    categories: ['DevOps', 'CI/CD', 'GitHub Actions'],
  },
  {
    id: 'mock-5',
    title: 'Database Design Patterns for High Performance',
    description: 'Explore advanced database design patterns that improve performance and scalability. Learn about indexing strategies, query optimization, and data modeling best practices.',
    link: 'https://medium.com/@hpitawela/database-design-patterns',
    pubDate: new Date('2023-12-20'),
    thumbnail: 'https://via.placeholder.com/400x200/f44336/ffffff?text=Database+Design',
    author: 'Harsha Pitawela',
    categories: ['Database', 'Performance', 'SQL'],
  },
  {
    id: 'mock-6',
    title: 'Container Orchestration with Kubernetes',
    description: 'Master container orchestration using Kubernetes. This guide covers pod management, service discovery, scaling strategies, and monitoring in production environments.',
    link: 'https://medium.com/@hpitawela/kubernetes-orchestration',
    pubDate: new Date('2023-12-15'),
    thumbnail: 'https://via.placeholder.com/400x200/2196f3/ffffff?text=Kubernetes',
    author: 'Harsha Pitawela',
    categories: ['Kubernetes', 'Containers', 'DevOps'],
  },
];